<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <RootNamespace>Sample.Shipping.Worker</RootNamespace>
    <UserSecretsId>sample-shipping-worker</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/PubSub.Client/PubSub.Client.csproj" />
    <ProjectReference Include="../../src/PubSub.Outbox/PubSub.Outbox.csproj" />
  </ItemGroup>

</Project>
