<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PubSub.Broker.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/PubSub.Broker.Core/PubSub.Broker.Core.csproj" />
    <ProjectReference Include="../../src/PubSub.Broker.Redis/PubSub.Broker.Redis.csproj" />
    <ProjectReference Include="../../src/PubSub.Outbox/PubSub.Outbox.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

</Project>
