// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PubSub.Broker.Core;

#nullable disable

namespace PubSub.Broker.Core.Storage.Migrations
{
    [DbContext(typeof(BrokerDbContext))]
    [Migration("20260827052546_InitialBrokerSchema")]
    partial class InitialBrokerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PubSub.Broker.Core.DedupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_DedupEntries_Expiry");

                    b.HasIndex("TopicId", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("UX_DedupEntries_MessageId");

                    b.ToTable("DedupEntries", (string)null);
                });

            modelBuilder.Entity("PubSub.Broker.Core.DeliveryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeadLetterDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("DeadLetterReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("MessageSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("OverriddenPropertiesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageSequenceNumber");

                    b.HasIndex("State", "ExpiresAt")
                        .HasDatabaseName("IX_Deliveries_Expiry");

                    b.HasIndex("State", "LockedUntil")
                        .HasDatabaseName("IX_Deliveries_LockExpiry");

                    b.HasIndex("SubscriptionId", "SequenceNumber")
                        .HasDatabaseName("IX_Deliveries_Sequence");

                    b.HasIndex("SubscriptionId", "State", "SettledAt")
                        .HasDatabaseName("IX_Deliveries_Settled");

                    b.HasIndex("SubscriptionId", "SessionId", "State", "SequenceNumber")
                        .HasDatabaseName("IX_Deliveries_SessionClaim");

                    b.HasIndex("SubscriptionId", "State", "AvailableAt", "SequenceNumber")
                        .HasDatabaseName("IX_Deliveries_Claim");

                    b.ToTable("Deliveries", (string)null);
                });

            modelBuilder.Entity("PubSub.Broker.Core.MessageEntity", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("ApplicationPropertiesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTimeOffset>("EnqueuedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ReplyToSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Subject")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("To")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("TopicId", "ExpiresAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("PubSub.Broker.Core.RuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionExpression")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FilterKind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SqlExpression")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "Name")
                        .IsUnique();

                    b.ToTable("Rules", (string)null);
                });

            modelBuilder.Entity("PubSub.Broker.Core.SessionLockEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LockToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("State")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LockedUntil")
                        .HasDatabaseName("IX_SessionLocks_Expiry");

                    b.HasIndex("SubscriptionId", "SessionId")
                        .IsUnique()
                        .HasDatabaseName("UX_SessionLocks_Session");

                    b.ToTable("SessionLocks", (string)null);
                });

            modelBuilder.Entity("PubSub.Broker.Core.SubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("DeadLetterOnFilterEvaluationError")
                        .HasColumnType("bit");

                    b.Property<bool>("DeadLetterOnMessageExpiration")
                        .HasColumnType("bit");

                    b.Property<long?>("DefaultTimeToLive")
                        .HasColumnType("bigint");

                    b.Property<long>("LockDuration")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxDeliveryCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("ReceivingSuspended")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresSession")
                        .HasColumnType("bit");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("int");

                    b.Property<long>("SessionLockDuration")
                        .HasColumnType("bigint");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "Name")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("PubSub.Broker.Core.TopicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("DefaultTimeToLive")
                        .HasColumnType("bigint");

                    b.Property<bool>("DuplicateDetectionEnabled")
                        .HasColumnType("bit");

                    b.Property<long>("DuplicateDetectionWindow")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxMessageSizeBytes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("PublishingSuspended")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("PubSub.Broker.Core.DeliveryEntity", b =>
                {
                    b.HasOne("PubSub.Broker.Core.MessageEntity", "Message")
                        .WithMany("Deliveries")
                        .HasForeignKey("MessageSequenceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PubSub.Broker.Core.SubscriptionEntity", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PubSub.Broker.Core.MessageEntity", b =>
                {
                    b.HasOne("PubSub.Broker.Core.TopicEntity", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("PubSub.Broker.Core.RuleEntity", b =>
                {
                    b.HasOne("PubSub.Broker.Core.SubscriptionEntity", "Subscription")
                        .WithMany("Rules")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PubSub.Broker.Core.SessionLockEntity", b =>
                {
                    b.HasOne("PubSub.Broker.Core.SubscriptionEntity", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PubSub.Broker.Core.SubscriptionEntity", b =>
                {
                    b.HasOne("PubSub.Broker.Core.TopicEntity", "Topic")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("PubSub.Broker.Core.MessageEntity", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("PubSub.Broker.Core.SubscriptionEntity", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("PubSub.Broker.Core.TopicEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
